### ISSUE TITLE
there is no the definition of reduce_matrix.

### ISSUE THREAD

**Issue by xiaoyukaka** [TRIQS/hubbardI#2]
Hi developers,
When I test the example:Ce with Hubbard-I approximation, I try to run DFT+DMFT calculations by "pytriqs Ce-gamma.py". There is an error, as follows:

.........
DC energy for shell 0 = 0.00418670427203
Traceback (most recent call last):
  File "Ce.py", line 75, in <module>
    S.solve(U_int=U, J_hund=J, T=None)
  File "path..../pytriqs/applications/impurity_solvers/hubbard_I/hubbard_solver.py", line 88, in solve
    ur,umn,ujmn=self.__set_umatrix(U=U_int,J=J_hund,T=T)
  File "path..../pytriqs/applications/impurity_solvers/hubbard_I/hubbard_solver.py", line 257, in __set_umatrix
    Umat.reduce_matrix()
AttributeError: 'numpy.ndarray' object has no attribute 'reduce_matrix'

I can not find the def of reduce_matrix. but the "def reduce_4index_to_2index(U_4index)" in U_matrix.py.   Need I replace it in hubbard_solver.py?

**Comment by pseth** [comment]
I have fixed this.
